import React, { Component } from "react";
import { connect } from "react-redux";
import { Container, Content, Text, Button, Icon, View } from 'native-base';
import { bindActionCreators } from "redux";
import * as userActions from '../../Actions/UserActions';
import FastImage from 'react-native-fast-image';
import { Image, StyleSheet } from "react-native";
import * as assetActions from '../../Actions/AssetActions';
let background = require("../Login/Images/vie_logo.png");
export class UserLicenseAgreement extends Component {

    constructor(props, context) {
        super(props, context);
      /*  this.state = {
            isButtonDisabled: true
        }*/
    }

   // componentDidMount = () => {
       // this.props.assetActions.userLicenceloadAllAssetsFromApi(this.props.customerId);
  //  }
    // shouldComponentUpdate = (nextProps, nextState) => {
    //     console.log("shouldComponentUpdate", this.state.isButtonDisabled)
    //     if (this.props.assets != nextProps.assets && this.props.users != nextProps.users) {
    //         this.setState({ isButtonDisabled: false })
    //     }
    //     return true;
    // }

  /*  componentWillReceiveProps(nextProps) {
        if (nextProps.users != this.props.users) {
            this.setState({ isButtonDisabled: false })
        }
    }*/

    agreeButtonClick = () => {
        this.props.userActions.userLicenceAgreeButtonClick();
    }


    render() {
        const B = (props) => <Text style={{ fontWeight: 'bold' }}>{props.children}</Text>
        return (
            <Container>
                <Content style={{ padding: 10 }}>
                    <View style={{ justifyContent: "center", alignItems: "center" }}>
                        <Image
                            style={{ width: 300, height: 300 }}
                            resizeMode="contain"
                            source={background}
                        />
                        <Text style={{ justifyContent: "center", alignItems: "center", fontWeight: 'bold', fontSize: 25 }}>Terms of Service agreement</Text>
                        <Text style={{ alignSelf: 'flex-start', fontStyle: "italic", paddingTop: 10, paddingBottom: 10 }}>Last Updated: November 2, 2018</Text>
                        <Text style={styles.align}>THANK YOU FOR USING OUR PRODUCTS AND SERVICES (“SERVICES”). THE SERVICES ARE PROVIDED BY VIE TECHNOLOGIES, INC (“VIE”), A DELAWARE CORPORATION LOCATED AT 9474 KEARNEY VILLA, SUITE 105, SAN DIEGO, 92126, UNITED STATES.</Text>
                        <Text style={styles.align}>BY PRESSING THE “I ACCEPT” BUTTON DURING INSTALLATION, LOGIN OR USE, YOU ARE AGREEING TO THESE TERMS. PLEASE READ THEM CAREFULLY</Text>
                        <Text style={styles.heading}>1.	Definitions</Text>
                        <Text style={styles.align}>1.1 In this Agreement, except to the extent expressly provided otherwise:</Text>
                        <Text style={styles.align}><B>"Account"</B> means an account enabling a person to access and use the Hosted Services, including both administrator accounts and user accounts;</Text>
                        <Text style={styles.align}><B>"Agreement"</B> means this agreement including any Schedules, and any amendments to this Agreement from time to time;</Text>
                        <Text style={styles.align}><B>"Business Day"</B> means any weekday other than a bank or public holiday in the United States;</Text>
                        <Text style={styles.align}><B>"Business Hours"</B> means the hours of 09:00 to 17:00 PST/PDT on a Business Day;</Text>
                        <Text style={styles.align}><B>"Charges"</B> means the following amounts such amounts as may be agreed in writing by the parties from time to time</Text>
                        <Text style={styles.align}><B>"Customer Confidential Information"</B> means:</Text>
                        <Text>(a)	any information disclosed by or on behalf of the Customer to the Provider during the Term (whether disclosed in writing, orally or otherwise) that at the time of disclosure:</Text>
                        <Text>(i)	was marked or described as "confidential"</Text>
                        <Text style={styles.align}>(b)	the Customer Data;</Text>
                        <Text style={styles.align}><B>"Customer Data"</B> means all data, works and materials: uploaded to or stored on the Platform by the Customer; transmitted by the Platform at the instigation of the Customer; supplied by the Customer to the Provider for uploading to, transmission by or storage on the Platform; or generated by the Platform as a result of the use of the Hosted Services by the Customer (but excluding analytics data relating to the use of the Platform and server log files); </Text>
                        <Text style={styles.align}><B>"Customer Personal Data"</B> means any Personal Data that is processed by the Provider on behalf of the Customer in relation to this Agreement, but excluding data with respect to which the Provider is a data controller; </Text>
                        <Text style={styles.align}><B>"Data Protection Laws"</B> means all applicable laws relating to the processing of Personal Data including, while it is in force and applicable to Customer Personal Data, the General Data Protection Regulation (Regulation (EU) 2016/679); </Text>
                        <Text style={styles.align}><B>"Documentation"</B> means the documentation for the Hosted Services produced by the Provider and delivered or made available by the Provider to the Customer; </Text>
                        <Text style={styles.align}><B>"Effective Date"</B> means the date of execution of this Agreement; </Text>
                        <Text style={styles.align}><B>"Force Majeure Event"</B> means an event, or a series of related events, that is outside the reasonable control of the party affected (including failures of the internet or any public telecommunications network, hacker attacks, denial of service attacks, virus or other malicious software attacks or infections, power failures, industrial disputes affecting any third party, changes to the law, disasters, explosions, fires, floods, riots, terrorist attacks and wars);</Text>
                        <Text style={styles.align}><B>"Hosted Services"</B> means OPA services which will be made available by the Provider to the Customer as a service via the internet in accordance with this Agreement; </Text>
                        <Text style={styles.align}><B>"Hosted Services Defect"</B> means a defect, error or bug in the Platform having a material adverse effect on the appearance, operation, functionality or performance of the Hosted Services, but excluding any defect, error or bug caused by or arising as a result of: </Text>
                        <Text style={styles.align}>(a)	any act or omission of the Customer or any person authorised by the Customer to use the Platform or Hosted Services;</Text>
                        <Text style={styles.align}>(b)	any use of the Platform or Hosted Services contrary to the Documentation, whether by the Customer or by any person authorized by the Customer;</Text>
                        <Text style={styles.align}>(c)	a failure of the Customer to perform or observe any of its obligations in this Agreement; and/or</Text>
                        <Text style={styles.align}>(d)	an incompatibility between the Platform or Hosted Services and any other system, network, application, program, hardware or software not specified as compatible in the Hosted Services Specification;</Text>
                        <Text style={styles.align}><B>"Hosted Services Specification"</B>  means the specification for the Platform and Hosted Services set out in the Documentation;</Text>
                        <Text style={styles.align}><B>"Intellectual Property Rights"</B> means all intellectual property rights wherever in the world, whether registrable or unregistrable, registered or unregistered, including any application or right of application for such rights (and these "intellectual property rights" include copyright and related rights, database rights, confidential information, trade secrets, know-how, business names, trade names, trade marks, service marks, passing off rights, unfair competition rights, patents, petty patents, utility models, semi-conductor topography rights and rights in designs); </Text>
                        <Text style={styles.align}><B>"Maintenance Services"</B> means the general maintenance of the Platform and Hosted Services, and the application of Updates and Upgrades; </Text>
                        <Text style={styles.align}><B>"Mobile App"</B> means the mobile application that is made available by the Provider; </Text>
                        <Text style={styles.align}><B>"Personal Data"</B> has the meaning given to it in the Data Protection Laws applicable in the United States from time to time; </Text>
                        <Text style={styles.align}><B>"Platform"</B> means the platform managed by the Provider and used by the Provider to provide the Hosted Services, including the application and database software for the Hosted Services, the system and server software used to provide the Hosted Services, and the computer hardware on which that application, database, system and server software is installed; </Text>
                        <Text style={styles.align}><B>"Schedule"</B> means any schedule attached to the main body of this Agreement; </Text>
                        <Text style={styles.align}><B>"Services"</B> means any services that the Provider provides to the Customer, or has an obligation to provide to the Customer, under this Agreement; </Text>
                        <Text style={styles.align}><B>"Support Services"</B> means support in relation to the use of, and the identification and resolution of errors in, the Hosted Services, but shall not include the provision of training services; </Text>
                        <Text style={styles.align}><B>"Supported Web Browser"</B> means the current release from time to time of Microsoft Edge, Mozilla Firefox, Google Chrome or Apple Safari, or any other web browser that the Provider agrees in writing shall be supported; </Text>
                        <Text style={styles.align}><B>"Term"</B> means the term of this Agreement, commencing in accordance with Clause 3.1 and ending in accordance with Clause 3.2; </Text>
                        <Text style={styles.align}><B>"Update"</B> means a hotfix, patch or minor version update to any Platform software; and </Text>
                        <Text style={styles.align}><B>"Upgrade"</B> means a major version upgrade of any Platform software. </Text>
                        <Text style={styles.heading}>2.	Credit</Text>
                        <Text style={styles.align}>2.1	This document was created using a template from SEQ Legal (https://seqlegal.com).</Text>
                        <Text style={styles.heading}>3.	Term</Text>
                        <Text style={styles.align}>3.1	This Agreement shall come into force upon the Effective Date.</Text>
                        <Text style={styles.align}>3.2	This Agreement shall continue in force indefinitely, subject to termination in accordance with Clause 18 or any other provision of this Agreement.</Text>
                        <Text style={styles.heading}>4.	Hosted Services</Text>
                        <Text style={styles.align}>4.1	(Intentionally omitted)</Text>
                        <Text style={styles.align}>4.2	The Provider hereby grants to the Customer a worldwide, non-exclusive licence to use the Hosted Services by means of in accordance with the Documentation during the Term.</Text>
                        <Text style={styles.align}>4.3	The licence granted by the Provider to the Customer under Clause 4.2 is subject to the following limitations:</Text>
                        <Text style={styles.align}>(a)	the Hosted Services may only be used by the officers, employees, agents and subcontractors of the Customer;</Text>
                        <Text style={styles.align}>(b)   (Intentionally omitted)</Text>
                        <Text style={styles.align}>(c)	the Hosted Services must not be used at any point in time by more than the number of users specified in the Document</Text>
                        <Text style={styles.align}>4.4	Except to the extent expressly permitted in this Agreement or required by law on a non-excludable basis, the licence granted by the Provider to the Customer under Clause 4.2 is subject to the following prohibitions:</Text>
                        <Text style={styles.align}>(a)	the Customer must not sub-license its right to access and use the Hosted Services;</Text>
                        <Text style={styles.align}>(b)	the Customer must not permit any unauthorised person to access or use the Hosted Services;</Text>
                        <Text style={styles.align}>(c)	the Customer must not use the Hosted Services to provide services to third parties;</Text>
                        <Text style={styles.align}>(d)	the Customer must not republish or redistribute any content or material from the Hosted Services;</Text>
                        <Text style={styles.align}>(e)	the Customer must not make any alteration to the Platform; and</Text>
                        <Text style={styles.align}>(f)	the Customer must not conduct or request that any other person conduct any load testing or penetration testing on the Platform or Hosted Services.</Text>
                        <Text style={styles.align}>4.5	The Customer shall use reasonable endeavours, including reasonable security measures relating to Account access details, to ensure that no unauthorised person may gain access to the Hosted Services using an Account.</Text>
                        <Text style={styles.align}>4.6	The Provider shall use reasonable endeavours to maintain the availability of the Hosted Services to the Customer but does not guarantee 100% availability.</Text>
                        <Text style={styles.align}>4.7	For the avoidance of doubt, downtime caused directly or indirectly by any of the following shall not be considered a breach of this Agreement:</Text>
                        <Text style={styles.align}>(a)	a Force Majeure Event;</Text>
                        <Text style={styles.align}>(b)	a fault or failure of the internet or any public telecommunications network;</Text>
                        <Text style={styles.align}>(c)	a fault or failure of the Customer's computer systems or networks;</Text>
                        <Text style={styles.align}>(d)	any breach by the Customer of this Agreement; or</Text>
                        <Text style={styles.align}>(e)	scheduled maintenance carried out in accordance with this Agreement.</Text>
                        <Text style={styles.align}>4.8	(Intentionally omitted)</Text>
                        <Text style={styles.align}>4.9	The Customer must not use the Hosted Services in any way that causes, or may cause, damage to the Hosted Services or Platform or impairment of the availability or accessibility of the Hosted Services.</Text>
                        <Text style={styles.align}>4.10	The Customer must not use the Hosted Services:</Text>
                        <Text style={styles.align}>(a)	in any way that is unlawful, illegal, fraudulent or harmful; or</Text>
                        <Text style={styles.align}>(b)	in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.</Text>
                        <Text style={styles.align}>4.11	For the avoidance of doubt, the Customer has no right to access the software code (including object code, intermediate code and source code) of the Platform, either during or after the Term.</Text>
                        <Text style={styles.align}>4.12	The Provider may suspend the provision of the Hosted Services if any amount due to be paid by the Customer to the Provider under this Agreement is overdue, and the Provider has given to the Customer at least 30 days' written notice, following the amount becoming overdue, of its intention to suspend the Hosted Services on this basis.</Text>
                        <Text style={styles.heading}>5.	Maintenance Services</Text>
                        <Text style={styles.align}>5.1	The Provider shall provide the Maintenance Services to the Customer during the Term.</Text>
                        <Text style={styles.align}>5.2	The Provider shall where practicable give to the Customer prior written notice of scheduled Maintenance Services that are likely to affect the availability of the Hosted Services or are likely to have a material negative impact upon the Hosted Services, without prejudice to the Provider's other notice obligations under this main body of this Agreement.</Text>
                        <Text style={styles.align}>5.3	The Provider shall give to the Customer prior written notice of the application of an Upgrade to the Platform.</Text>
                        <Text style={styles.align}>5.4	The Provider shall give to the Customer written notice of the application of any security Update to the Platform and prior written notice of the application of any non-security Update to the Platform.</Text>
                        <Text style={styles.align}>5.5	(Intentionally omitted)</Text>
                        <Text style={styles.align}>5.6	The Provider may suspend the provision of the Maintenance Services if any amount due to be paid by the Customer to the Provider under this Agreement is overdue, and the Provider has given to the Customer at least 30 days' written notice, following the amount becoming overdue, of its intention to suspend the Maintenance Services on this basis.</Text>
                        <Text style={styles.heading}>6. </Text>
                        <Text style={styles.heading}>7.	Customer Data</Text>
                        <Text style={styles.align}>7.1	The Customer hereby grants to the Provider a non-exclusive licence to copy, reproduce, store, distribute, publish, export, adapt, edit and translate the Customer Data to the extent reasonably required for the performance of the Provider's obligations and the exercise of the Provider's rights under this Agreement. The Customer also grants to the Provider the right to sub-license these rights to its hosting, connectivity and telecommunications service providers, subject to any express restrictions elsewhere in this Agreement.</Text>
                        <Text style={styles.align}>7.2	The Customer warrants to the Provider that the Customer Data will not infringe the Intellectual Property Rights or other legal rights of any person, and will not breach the provisions of any law, statute or regulation, in any jurisdiction and under any applicable law.</Text>
                        <Text style={styles.align}>7.3	(Intentionally omitted)</Text>
                        <Text style={styles.align}>7.4	The Provider shall use all reasonable endeavours to restore to the Platform the Customer Data stored. The Customer acknowledges that this process will overwrite the Customer Data stored on the Platform prior to the restoration.</Text>
                        <Text style={styles.heading}>8.	Mobile App</Text>
                        <Text style={styles.align}>8.1	The parties acknowledge and agree that the use of the Mobile App, the parties' respective rights and obligations in relation to the Mobile App and any liabilities of either party arising out of the use of the Mobile App shall be subject to separate terms and conditions, and accordingly this Agreement shall not govern any such use, rights, obligations or liabilities.</Text>
                        <Text style={styles.heading}>9.	No assignment of Intellectual Property Rights</Text>
                        <Text style={styles.align}>9.1	Nothing in this Agreement shall operate to assign or transfer any Intellectual Property Rights from the Provider to the Customer, or from the Customer to the Provider.</Text>
                        <Text style={styles.heading}>10.	Charges</Text>
                        <Text style={styles.align}>10.1	The Customer shall pay the Charges to the Provider in accordance with this Agreement.</Text>
                        <Text style={styles.align}>10.2	(Intentionally omitted)</Text>
                        <Text style={styles.align}>10.3	(Intentionally omitted)</Text>
                        <Text style={styles.align}>10.4	(Intentionally omitted)</Text>
                        <Text style={styles.heading}>11. </Text>
                        <Text style={styles.heading}>12.	Provider's confidentiality obligations</Text>
                        <Text style={styles.align}>12.1	The Provider must:</Text>
                        <Text style={styles.align}>(a)	keep the Customer Confidential Information strictly confidential;</Text>
                        <Text style={styles.align}>(b)	not disclose the Customer Confidential Information to any person without the Customer's prior written consent;</Text>
                        <Text style={styles.align}>(c)	use the same degree of care to protect the confidentiality of the Customer Confidential Information as the Provider uses to protect the Provider's own confidential information of a similar nature, being at least a reasonable degree of care;</Text>
                        <Text style={styles.align}>(d)	act in good faith at all times in relation to the Customer Confidential Information; and</Text>
                        <Text style={styles.align}>12.2	Notwithstanding Clause 12.1, the Provider may disclose the Customer Confidential Information to the Provider's officers, employees, professional advisers, insurers, agents and subcontractors who have a need to access the Customer Confidential Information for the performance of their work with respect to this Agreement and who are bound by a written agreement or professional obligation to protect the confidentiality of the Customer Confidential Information.</Text>
                        <Text style={styles.align}>12.3	This Clause 12 imposes no obligations upon the Provider with respect to Customer Confidential Information that:</Text>
                        <Text style={styles.align}>(a)	is known to the Provider before disclosure under this Agreement and is not subject to any other obligation of confidentiality;</Text>
                        <Text style={styles.align}>(b)	is or becomes publicly known through no act or default of the Provider; or</Text>
                        <Text style={styles.align}>(c)	is obtained by the Provider from a third party in circumstances where the Provider has no reason to believe that there has been a breach of an obligation of confidentiality.</Text>
                        <Text style={styles.align}>12.4	The restrictions in this Clause 12 do not apply to the extent that any Customer Confidential Information is required to be disclosed by any law or regulation, by any judicial or governmental order or request, or pursuant to disclosure requirements relating to the listing of the stock of the Provider on any recognised stock exchange.</Text>
                        <Text style={styles.align}>12.5	The provisions of this Clause 12 shall continue in for a period of 5 years following the termination of this Agreement, at the end of which period they will cease to have effect.</Text>
                        <Text style={styles.heading}>13.	Data protection</Text>
                        <Text style={styles.align}>13.1	The Provider shall comply with the Data Protection Laws with respect to the processing of the Customer Personal Data.</Text>
                        <Text style={styles.align}>13.2	The Customer warrants to the Provider that it has the legal right to disclose all Personal Data that it does in fact disclose to the Provider under or in connection with this Agreement.</Text>
                        <Text style={styles.align}>13.3	The Customer shall only supply to the Provider, and the Provider shall only process, in each case under or in relation to this Agreement, the Personal Data of data subjects falling within the categories specified in Part 1 of Schedule 3 (Data processing information) and of the types specified in Part 2 of Schedule 3 (Data processing information); and the Provider shall only process the Customer Personal Data for the purposes specified in Part 3 of Schedule 3 (Data processing information).</Text>
                        <Text style={styles.align}>13.4	The Provider shall only process the Customer Personal Data during the Term and for not more than 90 days following the end of the Term, subject to the other provisions of this Clause 13.</Text>
                        <Text style={styles.align}>13.5	The Provider shall only process the Customer Personal Data on the documented instructions of the Customer (including with regard to transfers of the Customer Personal Data, as set out in this Agreement or any other document agreed by the parties in writing.</Text>
                        <Text style={styles.align}>13.6	(Intentionally omitted)</Text>
                        <Text style={styles.align}>13.7	Notwithstanding any other provision of this Agreement, the Provider may process the Customer Personal Data if and to the extent that the Provider is required to do so by applicable law. In such a case, the Provider shall inform the Customer of the legal requirement before processing, unless that law prohibits such information.</Text>
                        <Text style={styles.align}>13.8	The Provider shall ensure that persons authorised to process the Customer Personal Data have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality.</Text>
                        <Text style={styles.align}>13.9	The Provider and the Customer shall each implement appropriate technical and organisational measures to ensure an appropriate level of security for the Customer Personal Data.</Text>
                        <Text style={styles.align}>13.10	The Provider must not engage any third party to process the Customer Personal Data without the prior specific or general written authorisation of the Customer. In the case of a general written authorisation, the Provider shall inform the Customer at least 30 days in advance of any intended changes concerning the addition or replacement of any third party processor, and if the Customer objects to any such changes before their implementation, then the Customer may terminate this Agreement on 7 days' written notice to the Provider, providing that such notice must be given within the period of 7 days following the date that the Provider informed the Customer of the intended changes. The Provider shall ensure that each third party processor is subject to equivalent legal obligations as those imposed on the Provider by this Clause 13.</Text>
                        <Text style={styles.align}>13.11	(Intentionally omitted)</Text>
                        <Text style={styles.align}>13.12	The Provider shall, insofar as possible and taking into account the nature of the processing, take appropriate technical and organisational measures to assist the Customer with the fulfilment of the Customer's obligation to respond to requests exercising a data subject's rights under the Data Protection Laws.</Text>
                        <Text style={styles.align}>13.13	The Provider shall assist the Customer in ensuring compliance with the obligations relating to the security of processing of personal data, the notification of personal data breaches to the supervisory authority, the communication of personal data breaches to the data subject, data protection impact assessments and prior consultation in relation to high-risk processing under the Data Protection Laws.</Text>
                        <Text style={styles.align}>13.14	The Provider shall make available to the Customer all information necessary to demonstrate the compliance of the Provider with its obligations under this Clause 13 and the Data Protection Laws.</Text>
                        <Text style={styles.align}>13.15	The Provider shall, at the choice of the Customer, delete or return all of the Customer Personal Data to the Customer after the provision of services relating to the processing, and shall delete existing copies save to the extent that applicable law requires storage of the relevant Personal Data.</Text>
                        <Text style={styles.align}>13.16	The Provider shall allow for and contribute to audits, including inspections, conducted by the Customer or another auditor mandated by the Customer in respect of the compliance of the Provider's processing of Customer Personal Data with the Data Protection Laws and this Clause 13. The Provider may charge the Customer for any work performed by the Provider at the request of the Customer pursuant to this Clause 13.16.</Text>
                        <Text style={styles.align}>13.17	(Intentionally omitted)</Text>
                        <Text style={styles.heading}>14.	Warranties</Text>
                        <Text style={styles.align}>14.1	The Provider warrants to the Customer that:</Text>
                        <Text style={styles.align}>(a)	the Provider has the legal right and authority to enter into this Agreement and to perform its obligations under this Agreement;</Text>
                        <Text style={styles.align}>(b)	the Provider will comply with all applicable legal and regulatory requirements applying to the exercise of the Provider's rights and the fulfilment of the Provider's obligations under this Agreement; and</Text>
                        <Text style={styles.align}>(c)	the Provider has or has access to all necessary know-how, expertise and experience to perform its obligations under this Agreement.</Text>
                        <Text style={styles.align}>14.2	(Intentionally omitted)</Text>
                        <Text style={styles.align}>14.3	(Intentionally omitted)</Text>
                        <Text style={styles.align}>14.4	(Intentionally omitted)</Text>
                        <Text style={styles.align}>14.5	If the Provider reasonably determines, or any third party alleges, that the use of the Hosted Services by the Customer in accordance with this Agreement infringes any person's Intellectual Property Rights, the Provider may at its own cost and expense:</Text>
                        <Text style={styles.align}>(a)	modify the Hosted Services in such a way that they no longer infringe the relevant Intellectual Property Rights; or</Text>
                        <Text style={styles.align}>(b)	procure for the Customer the right to use the Hosted Services in accordance with this Agreement.</Text>
                        <Text style={styles.align}>14.6	The Customer warrants to the Provider that it has the legal right and authority to enter into this Agreement and to perform its obligations under this Agreement.</Text>
                        <Text style={styles.align}>14.7	All of the parties' warranties and representations in respect of the subject matter of this Agreement are expressly set out in this Agreement. To the maximum extent permitted by applicable law, no other warranties or representations concerning the subject matter of this Agreement will be implied into this Agreement or any related contract.</Text>
                        <Text style={styles.heading}>15.	Acknowledgements and warranty limitations</Text>
                        <Text style={styles.align}>15.1	The Customer acknowledges that complex software is never wholly free from defects, errors and bugs; and subject to the other provisions of this Agreement, the Provider gives no warranty or representation that the Hosted Services will be wholly free from defects, errors and bugs.</Text>
                        <Text style={styles.align}>15.2	The Customer acknowledges that complex software is never entirely free from security vulnerabilities; and subject to the other provisions of this Agreement, the Provider gives no warranty or representation that the Hosted Services will be entirely secure.</Text>
                        <Text style={styles.align}>15.3	The Customer acknowledges that the Hosted Services are designed to be compatible only with specified software and systems; and the Provider does not warrant or represent that the Hosted Services will be compatible with any other software or systems.</Text>
                        <Text style={styles.align}>15.4	(Intentionally omitted)</Text>
                        <Text style={styles.heading}>16.	Limitations and exclusions of liability</Text>
                        <Text style={styles.align}>16.1	Nothing in this Agreement will:</Text>
                        <Text style={styles.align}>(a)	limit or exclude any liability for death or personal injury resulting from negligence;</Text>
                        <Text style={styles.align}>(b)	limit or exclude any liability for fraud or fraudulent misrepresentation;</Text>
                        <Text style={styles.align}>(c)	limit any liabilities in any way that is not permitted under applicable law; or</Text>
                        <Text style={styles.align}>(d)	exclude any liabilities that may not be excluded under applicable law.</Text>
                        <Text style={styles.align}>16.2	(Intentionally omitted)</Text>
                        <Text style={styles.align}>16.3	(Intentionally omitted)</Text>
                        <Text style={styles.align}>16.4	(Intentionally omitted)</Text>
                        <Text style={styles.align}>16.5	(Intentionally omitted)</Text>
                        <Text style={styles.align}>16.6	(Intentionally omitted)</Text>
                        <Text style={styles.align}>16.7	(Intentionally omitted)</Text>
                        <Text style={styles.align}>16.8	(Intentionally omitted)</Text>
                        <Text style={styles.align}>16.9	The Provider shall not be liable to the Customer in respect of any special, indirect or consequential loss or damage.</Text>
                        <Text style={styles.align}>16.10	The liability of the Provider to the Customer under this Agreement in respect of any event or series of related events shall not exceed the total amount paid and payable by the Customer to the Provider under this Agreement in the 12 month period preceding the commencement of the event or events.</Text>
                        <Text style={styles.align}>16.11(Intentionally omitted)</Text>
                        <Text style={styles.heading}>17.	(Intentionally omitted)</Text>
                        <Text style={styles.heading}>18.	Termination</Text>
                        <Text style={styles.align}>18.1	Either party may terminate this Agreement by giving to the other party at least 30 days' written notice of termination.</Text>
                        <Text style={styles.align}>18.2	Either party may terminate this Agreement immediately by giving written notice of termination to the other party if the other party commits a material breach of this Agreement.</Text>
                        <Text style={styles.align}>18.3	Either party may terminate this Agreement immediately by giving written notice of termination to the other party if:</Text>
                        <Text style={styles.align}>(a)	the other party:</Text>
                        <Text style={styles.align}>(i)	is dissolved;</Text>
                        <Text style={styles.align}>(ii)	ceases to conduct all (or substantially all) of its business;</Text>
                        <Text style={styles.align}>(iii)	is or becomes unable to pay its debts as they fall due;</Text>
                        <Text style={styles.align}>(iv)	is or becomes insolvent or is declared insolvent; or</Text>
                        <Text style={styles.align}>(v)	convenes a meeting or makes or proposes to make any arrangement or composition with its creditors;</Text>
                        <Text style={styles.align}>(b)	an administrator, administrative receiver, liquidator, receiver, trustee, manager or similar is appointed over any of the assets of the other party; or</Text>
                        <Text style={styles.align}>(c)	an order is made for the winding up of the other party, or the other party passes a resolution for its winding up.</Text>
                        <Text style={styles.heading}>19.	Effects of termination</Text>
                        <Text style={styles.align}>19.1	Upon the termination of this Agreement, all of the provisions of this Agreement shall cease to have effect, save that the following provisions of this Agreement shall survive and continue to have effect (in accordance with their express terms or otherwise indefinitely): Clauses 1, 4.11, 8, 12, 13.1, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 13.10, 13.11, 13.12, 13.13, 13.14, 13.15, 13.16, 13.17, 16, 19, 22 and 23.</Text>
                        <Text style={styles.align}>19.2	Except to the extent that this Agreement expressly provides otherwise, the termination of this Agreement shall not affect the accrued rights of either party.</Text>
                        <Text style={styles.align}>19.3	Within 30 days following the termination of this Agreement for any reason, the Customer must pay to the Provider any Charges in respect of Services provided to the Customer before the termination of this Agreement.</Text>
                        <Text style={styles.heading}>20.	(Intentionally omitted)</Text>
                        <Text style={styles.heading}>21.	(Intentionally omitted)</Text>
                        <Text style={styles.heading}>22.	General</Text>
                        <Text style={styles.align}>22.1	(Intentionally omitted)</Text>
                        <Text style={styles.align}>22.2	(Intentionally omitted)</Text>
                        <Text style={styles.align}>22.3	This Agreement may not be varied except by a written document signed by or on behalf of each of the parties.</Text>
                        <Text style={styles.align}>22.4	Neither party may without the prior written consent of the other party assign, transfer, charge, license or otherwise deal in or dispose of any contractual rights or obligations under this Agreement.</Text>
                        <Text style={styles.align}>22.5	This Agreement is made for the benefit of the parties, and is not intended to benefit any third party or be enforceable by any third party. The rights of the parties to terminate, rescind, or agree any amendment, waiver, variation or settlement under or relating to this Agreement are not subject to the consent of any third party.</Text>
                        <Text style={styles.align}>22.6	(Intentionally omitted)</Text>
                        <Text style={styles.align}>22.7	This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware.</Text>
                        <Text style={styles.align}>22.8	(Intentionally omitted)</Text>
                        <Text style={styles.heading}>23.	(Intentionally omitted)</Text>
                        <Text style={styles.heading}>SCHEDULE 1 (INTENTIONALLY OMITTED)</Text>
                        <Text style={styles.heading}>SCHEDULE 2 (INTENTIONALLY OMITTED)</Text>
                    </View>
                    <View style={{ flex: 1, justifyContent: 'flex-start', alignItems: "center", paddingTop: 20, paddingBottom: 50 }}>
                        <View style={{ flex: 1 }}>
                            <Button
                                style={{
                                flexDirection: 'row',
                                justifyContent: 'center',
                                alignItems: 'center'
                            }}  textStyle={{ color: '#87838B' }} onPress={() => this.agreeButtonClick()} >
                                <Icon name="thumbs-up" />
                                <Text testID= {"agree-btn"}>I Agree</Text>
                            </Button>
                        </View>
                    </View>
                </Content>
            </Container>
        );
    }
}

function mapStateToProps(state, ownProps) {
    return {
        users: state.userReducer,
        assets: state.assetReducer
    }
};
function mapDispatchToProps(dispatch) {
    return {
        userActions: bindActionCreators(userActions, dispatch),
        assetActions: bindActionCreators(assetActions, dispatch)
    };
};

const styles = StyleSheet.create({
    heading: {
        fontWeight: 'bold',
        alignSelf: 'flex-start',
        paddingBottom: 10
    },
    align: {
        alignSelf: 'flex-start',
        paddingBottom: 10
    }
})

export default connect(mapStateToProps, mapDispatchToProps)(UserLicenseAgreement);
