//events
export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_NEW_EVENTS = 'LOAD_NEW_EVENTS';
export const LOAD_NEW_EVENTS_INFO = 'LOAD_NEW_EVENTS_INFO';
export const LOAD_EVENT_ERROR = 'LOAD_EVENT_ERROR';
export const LOAD_EVENT_PENDING = 'LOAD_EVENT_PENDING';
export const LOAD_EVENT_COMPLETE = 'LOAD_EVENT_COMPLETE';
export const LOAD_NEW_EVENT_PENDING = 'LOAD_NEW_EVENT_PENDING';
export const LOAD_CUR_EVENT_PAGE = 'LOAD_CUR_EVENT_PAGE';
export const APPEND_EVENT_COMMENT_ON_EVENTS = 'APPEND_EVENT_COMMENT_ON_EVENTS';
export const APPEND_EVENT_FOLLOW_ON_EVENTS = 'APPEND_EVENT_FOLLOW_ON_EVENTS';
export const APPEND_EVENTS_ON_TICKET_UPDATION = 'APPEND_EVENTS_ON_TICKET_UPDATION';
export const APPEND_SAVED_FEEDBACK_TO_EVENTS = 'APPEND_SAVED_FEEDBACK_TO_EVENTS';
export const SAVE_FEEDBACK_HAS_ERROR = 'SAVE_FEEDBACK_HAS_ERROR';
export const SAVE_FEEDBACK_SUCCESS = 'SAVE_FEEDBACK_SUCCESS';
export const SAVE_USER_POST_SUCCESS = 'SAVE_USER_POST_SUCCESS';
export const TICKET_CREATED_SUCCESS = 'TICKET_CREATED_SUCCESS';
export const APPEND_EVENTS_ON_TICKET_CREATION = 'APPEND_EVENTS_ON_TICKET_CREATION';
export const LOAD_FETCHED_OPEN_TICKETS_ID = 'LOAD_FETCHED_OPEN_TICKETS_ID';
export const LOAD_FETCHED_TICKET_EVENT = 'LOAD_FETCHED_TICKET_EVENT';
export const APPEND_EVENTS_ON_TICKET_ASSIGNED_CHANGE = 'APPEND_EVENTS_ON_TICKET_ASSIGNED_CHANGE';
export const SAVE_TICKET_ASSIGNED_TO_SUCCESS = 'SAVE_TICKET_ASSIGNED_TO_SUCCESS';
export const APPEND_TICKET_COMMENT_ON_EVENTS = 'APPEND_TICKET_COMMENT_ON_EVENTS';
export const APPEND_USER_EVENT_ON_EVENTS = 'APPEND_USER_EVENT_ON_EVENTS';
export const EVENTS_LAST_UPDATED = 'EVENTS_LAST_UPDATED';
export const LOAD_FEEDBACK_HISTORY = 'LOAD_FEEDBACK_HISTORY';
export const TICKET_HISTORY = 'TICKET_HISTORY';
export const APPEND_EVENTS_ON_NEW_TICKET ='APPEND_EVENTS_ON_NEW_TICKET';
export const FETCH_FEED_EVENT_BY_ASSETID = 'FETCH_FEED_EVENT_BY_ASSETID';
//ASSETS
export const LOAD_ASSETS = 'LOAD_ASSETS';
export const LOAD_ALL_ASSETS = 'LOAD_ALL_ASSETS';
export const LOAD_ASSETS_FROM_START = 'LOAD_ASSETS_FROM_START';
export const LOAD_ASSETS_ERROR = 'LOAD_ASSETS_ERROR';
export const LOAD_ASSETS_PENDING = 'LOAD_ASSETS_PENDING';
export const LOAD_ASSETS_COUNT = 'LOAD_ASSETS_COUNT';
export const LOAD_ASSETS_COUNT_PENDING = 'LOAD_ASSETS_COUNT_PENDING';
export const APPEND_TICKETID_ON_ASSOCIATED_TICKETS = 'APPEND_TICKETID_ON_ASSOCIATED_TICKETS';
export const LOAD_ALL_PROCESSED_DATA_FOR_AN_ASSET = 'LOAD_ALL_PROCESSED_DATA_FOR_AN_ASSET';
export const LOAD_PROCESSED_DATA_HAS_ERROR = 'LOAD_PROCESSED_DATA_HAS_ERROR';
export const LOAD_PROCESSED_DATA_PENDING = 'LOAD_PROCESSED_DATA_PENDING';
export const LOAD_ASSET_BYID = 'LOAD_ASSET_BYID';
export const LOAD_ASSET_OPERATIONAL_INFO = 'LOAD_ASSET_OPERATIONAL_INFO';
export const UPDATE_MOTE_STATE = 'UPDATE_MOTE_STATE'
export const LOAD_ASSET_TAGS = 'LOAD_ASSET_TAGS';
export const ONE_STEP_FEEDBACK_API_CALL_INITIATED = 'ONE_STEP_FEEDBACK_API_CALL_INITIATED';
export const ONE_STEP_FEEDBACK_RESULT = 'ONE_STEP_FEEDBACK_RESULT';
export const LOAD_ALL_ASSETS_BY_CUSTOMER_ID = 'LOAD_ALL_ASSETS_BY_CUSTOMER_ID';
//authentication
export const LOAD_LOGIN_RESPONSE = 'LOAD_LOGIN_RESPONSE';
export const UPDATE_LOGIN_RESPONSE = 'UPDATE_LOGIN_RESPONSE';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const TOKEN_EXPIRE = 'TOKEN_EXPIRE';
export const APP_UPGRADE = 'APP_UPGRADE';


export const CHANGEPASSWORD_ERROR = 'CHANGEPASSWORD_ERROR';
export const CHANGE_PASSWORD_RESPONSE = 'CHANGE_PASSWORD_RESPONSE';

//usersDetails
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_FROM_START = 'LOAD_USERS_FROM_START';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';
export const LOAD_USER_PENDING = 'LOAD_USER_PENDING';
export const LOAD_USERS_AFTER_START = 'LOAD_USERS_AFTER_START';
//Fault enums
export const LOAD_FAULT_ENUMS = 'LOAD_FAULT_ENUMS';
//force upgrade
export const FORCE_UPGRADE =  'FORCE_UPGRADE';
//Metrics
export const FETCH_GRAPH_METRICS = 'FETCH_GRAPH_METRICS';