export const MAIN_SCHEMA = 'MAIN_SCHEMA';
export const ASSET_SCHEMA = 'ASSET';
export const ASSET_COMMENTS = 'ASSET_COMMENTS';
export const ASSET_COMMENTID = 'ASSET_COMMENTID';
export const EVENT_SCHEMA = 'EVENT';
export const USER_SCHEMA = 'USER';
export const USER_COMMENTS = 'USER_COMMENTS';
export const USER_COMMENTID = 'USER_COMMENTID';
export const TICKET_SCHEMA = 'TICKET';
export const TICKET_COMMENTS = 'TICKET_COMMENTS';
export const TICKET_COMMENTID = 'TICKET_COMMENTID';
export const TICKET_EVENT_COMMENTS = 'TICKET_EVENT_COMMENTS';
export const TICKET_EVENT_COMMENTID = 'TICKET_EVENT_COMMENTID';


export const NEWFEED_SCHEMA = 'NEWFEED_SCHEMA';
export const NEWFEED_USER_SCHEMA = 'NEWFEED_USER_SCHEMA';
export const NEWFEED_USER_COMMENTS = 'NEWFEED_USER_COMMENTS';
export const NEWFEED_USER_COMMENTID = 'NEWFEED_USER_COMMENTID';
export const NEWFEED_TICKET_SCHEMA = 'NEWFEED_TICKET_SCHEMA';
export const NEWFEED_TICKET_COMMENTS = 'NEWFEED_TICKET_COMMENTS';
export const NEWFEED_TICKET_COMMENTID = 'NEWFEED_TICKET_COMMENTID';
export const NEWFEED_TICKET_EVENT_COMMENTS = 'NEWFEED_TICKET_EVENT_COMMENTS';
export const NEWFEED_TICKET_EVENT_COMMENTID = 'NEWFEED_TICKET_EVENT_COMMENTID';
export const NEWFEED_ASSET_SCHEMA = 'NEWFEED_ASSET';
export const NEWFEED_ASSET_COMMENTS = 'NEWFEED_ASSET_COMMENTS';
export const NEWFEED_ASSET_COMMENTID = 'NEWFEED_ASSET_COMMENTID';

export const LOGIN_SCHEMA = 'LOGIN_SCHEMA';
export const ASSETLIST_SCHEMA = 'ASSETLIST_SCHEMA';
export const ASSET_DETAILS_SCHEMA = 'ASSET_DETAILS_SCHEMA';
export const ASSET_BUBBLE_GRAPH = 'ASSET_BUBBLE_GRAPH';
export const FEEDBACK_HISTORY = 'FEEDBACK_HISTORY';
export const ASSET_OPERATIONAL_INFO = 'ASSET_OPERATIONAL_INFO';
export const CUSTOMER_ASSET_LIST = 'CUSTOMER_ASSET_LIST';
export const USERLIST_SCHEMA = 'USERLIST_SCHEMA';

export const PROCESSED_GRAPH_DATA = 'PROCESSED_GRAPH_DATA';
export const PROCCESED_GRAPHS = 'PROCCESED_GRAPHS';
export const PROCCESED_GRAPHS_POINTS = 'PROCCESED_GRAPHS_POINTS';

export const TICKET_HISTORY = 'TICKET_HISTORY';
export const ASSET_INTERVENTION_TIMELINE = 'ASSET_INTERVENTION_TIMELINE';
export const CUSTOMER_ASSET_INTERVENTION_TIMELINE = 'CUSTOMER_ASSET_INTERVENTION_TIMELINE';

export const ASSOCIATED_TICKETIDS_AND_STATUS = 'ASSOCIATED_TICKETIDS_AND_STATUS';

export const FORCE_UPGRADE = 'FORCE_UPGRADE';